"""initial

Revision ID: d0f63a1fa726
Revises:
Create Date: 2026-02-19 06:41:24.080320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0f63a1fa726'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strong_styles')
    op.drop_table('profile_elements')
    op.drop_column('heading_styles', 'hanging_indent')
    op.drop_column('heading_styles', 'bookmarked')
    op.drop_column('heading_styles', 'outlined')
    op.drop_column('heading_styles', 'offset')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heading_styles', sa.Column('offset', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('heading_styles', sa.Column('outlined', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('heading_styles', sa.Column('bookmarked', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.add_column('heading_styles', sa.Column('hanging_indent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_table('profile_elements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('element_type', postgresql.ENUM('bullet_list', 'document', 'figure', 'footnote', 'heading', 'numbered_list', 'par', 'quote', 'table', name='element_type_enum'), autoincrement=False, nullable=False),
    sa.Column('tight', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('marker1', sa.VARCHAR(length=64), server_default=sa.text("'- '::character varying"), autoincrement=False, nullable=False),
    sa.Column('marker2', sa.VARCHAR(length=64), server_default=sa.text("'‣'::character varying"), autoincrement=False, nullable=False),
    sa.Column('marker3', sa.VARCHAR(length=64), server_default=sa.text("'–'::character varying"), autoincrement=False, nullable=False),
    sa.Column('indent_pt', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('body_indent_em', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0.5'::double precision"), autoincrement=False, nullable=False),
    sa.Column('spacing', sa.VARCHAR(length=32), server_default=sa.text("'auto'::character varying"), autoincrement=False, nullable=False),
    sa.Column('spacing_em', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'1'::double precision"), autoincrement=False, nullable=False),
    sa.Column('font_size_pt', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'12'::double precision"), autoincrement=False, nullable=False),
    sa.Column('line_spacing_em', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'1.2'::double precision"), autoincrement=False, nullable=False),
    sa.Column('figure_width_em', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'1'::double precision"), autoincrement=False, nullable=False),
    sa.Column('figure_height_em', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('table_stroke', sa.VARCHAR(length=32), server_default=sa.text("'0.5pt'::character varying"), autoincrement=False, nullable=False),
    sa.Column('heading_numbering', sa.VARCHAR(length=64), server_default=sa.text("'1.1.1'::character varying"), autoincrement=False, nullable=False),
    sa.Column('quote_indent_em', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'1.5'::double precision"), autoincrement=False, nullable=False),
    sa.Column('footnote_marker_fmt', sa.VARCHAR(length=32), server_default=sa.text("'1'::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('profile_elements_profile_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('profile_elements_pkey')),
    sa.UniqueConstraint('profile_id', 'element_type', name=op.f('uq_profile_element_type'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('strong_styles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('delta', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('strong_styles_profile_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('strong_styles_pkey')),
    sa.UniqueConstraint('profile_id', name=op.f('strong_styles_profile_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
